### ISSUE TITLE
Para mim, não funciona :( 

### ISSUE THREAD

**Issue by alexalannunes** [Rocketseat/rocketpwa#1]
Usei o comando `sudo npm install -g rocketpwa`

> `alex@alex:~$ rocketpwa -h`
> `rocketpwa: comando não encontrado`
> `alex@alex:~$ `

- node: v8.11.3
- npm 6.4.1

Log de saída `sudo npm install -g rocketpwa`
[log.txt](https://github.com/Rocketseat/rocketpwa/files/2363284/log.txt)

**Comment by gregdusoli** [comment]
Exatamente o mesmo erro pra mim!

Segue detalhes sobre meu sistema:
![Screen Shot 2019-05-07 at 21 52 09](https://user-images.githubusercontent.com/15826492/57341884-7fdc3a00-7112-11e9-98ea-962605b83790.png)

**Comment by gregdusoli** [comment]
Bom dia, @diego3g!

Estou com a versão 12.1.0... será que pode ser porque eu estou usando a versão não LTS?

**Comment by gregdusoli** [comment]
> @alexalannunes Podes tentar com uma versão mais recente do Node? Fiz um teste aqui com a versão `10.9.0` e funcionou normalmente.
> 
> @gregdusoli Está com qual versão do Node e NPM?


Bom dia, @diego3g!

Estou com a versão 12.1.0... será que pode ser porque eu estou usando a versão não LTS?

**Comment by alexalannunes** [comment]
opa @diego3g 
**node** v10.15.1
**npm** 3.5.2

**Comment by diego3g** [comment]
@alexalannunes Podes tentar atualizar o NPM? Essa versão é bem antiga. 

@gregdusoli Versão 12 está com vários problemas, podes tentar uma versão LTS?

**Comment by gregdusoli** [comment]
> @alexalannunes Podes tentar atualizar o NPM? Essa versão é bem antiga.
> 
> @gregdusoli Versão 12 está com vários problemas, podes tentar uma versão LTS?

Opa @diego3g , vou tentar fazer o downgrade e depois te aviso, mas é meio ruim isso... uma vez tentei e só tive dor de cabeça.

**Comment by gregdusoli** [comment]
Removendo a versão 12 do Node e instalando a versão LTS deu certo!

Obrigado, @diego3g

**Comment by alexalannunes** [comment]
ja estou na v10.15 do node mas ainda da esse erro

```info sharp Using cached /home/alexalannunes/.npm/_libvips/libvips-8.6.1-linux-x64.tar.gz
ERR! sharp EACCES: permission denied, mkdir '/usr/local/lib/node_modules/rocketpwa/node_modules/sharp/vendor'
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/alexalannunes/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/rocketpwa/node_modules/sharp/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/rocketpwa/node_modules/sharp/.node-gyp'
gyp ERR! System Linux 4.4.0-145-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/rocketpwa/node_modules/sharp
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.20.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexalannunes/.npm/_logs/2019-05-12T12_58_12_541Z-debug.log```

**Comment by gregdusoli** [comment]
@alexalannunes uma coisa boba que já aconteceu comigo em outro projeto foi que eu estava tentando instalar um pacote NPM usando credencial root (sudo) e sempre dava erro. Eu resolvi digitar o comando `npm install <nome_do_pacote>` (sem sudo antes) e Voilà! A instalação transcorreu normalmente. 

Veja se, por acaso, não é isso que está acontecendo com você.

**Comment by alexalannunes** [comment]
@gregdusoli :+1: hehe Deu certo . \o 
Vlw amigão!!

**Comment by gregdusoli** [comment]
Maravilha, @alexalannunes !!! Fico feliz em ter ajudado de forma tão simples! Abraço, amigo!
